server:
  port: 8080

spring:
  application:
    name: dubbo-consumer

dubbo:
  service:
    version: 1.0
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  registry:
    id: registry_zookeeper
    address: zookeeper://192.168.101.54:2181